services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - /DATA/Downloads/Resilio Sync:/downloads
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend  # Make sure it points to the correct path
    ports:
      - "3000:80"
    depends_on:
      - backend
