services:
  yt-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /DATA/AppData/TY_files/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    environment:
      - FLASK_ENV=development
